<?php include('template/header5.php');?>
</div>
<div class="container">
	<div class="info-sec">
		<h1>Terms and Conditions</h1>

		<p>These Terms of Service ("Terms") apply to your access to and use of dlike.io and any other products or services that link to these Terms ("DLIKE"). DLIKE is a dapp on steem blockchain developed by BlockTalk Solutions Company (“DLIKE, “we” or “us”. By accessing or using DLIKE, you agree to be bound by these Terms. If you do not agree to these Terms, do not access or use DLIKE. If we make changes to these Terms, we will provide notice of those changes by updating the "Last Updated" date above or posting notice on DLIKE (website, mobile apps). Your continued use of DLIKE services will confirm your acceptance of the changes.</p>
		<p>You understand and agree that these Terms apply solely to your access to and use of DLIKE services and that, when you use other DLIKE services such as mobile apps, browser extensions and website, the terms and policies particular to those services apply.</p>
		<h2>1. Privacy Policy</h2>
		<p>Please refer to our <a href="/privacy" target="_blank">Privacy Policy</a> for information about how we collect, use and disclose information about you.</p>
		<h2>2. Eligibility</h2>
		<p>DLIKE is not targeted towards, nor intended for use by, anyone under the age of 18. You must be at least 18 years of age to access or use DLIKE.</p>
		<h2>3. Copyright and Limited License</h2>
		<p>DLIKE contains data, text, photographs, images, video, audio, graphics, articles, comments, software, code, scripts and other content supplied by us, the Steem blockchain or our licensors, which we call "DLIKE Content." DLIKE Content is protected by intellectual property laws, including copyright and other proprietary rights of applicable countries. Except as explicitly stated in these Terms, DLIKE does not grant any express or implied rights to use DLIKE Content.</p>
		<p>You are granted a limited, nonexclusive, non-transferable, and non-sublicensable license to access and use DLIKE and DLIKE Content for your personal, non-commercial use. This license is subject to these Terms and does not include any right to: (a) distribute, publicly perform or publicly display any DLIKE Content; (b) modify or otherwise make any derivative uses of DLIKE or DLIKE Content, or any portion thereof; (c) use any data mining, robots or similar data gathering or extraction methods; and (d) use DLIKE or DLIKE Content other than for their intended purposes. Any use of DLIKE or DLIKE Content other than as authorized in these Terms is strictly prohibited and will terminate the license granted herein. This license is revocable at any time.</p>
		<h2>4. Trademarks</h2>
		<p>"DLIKE", the DLIKE logo and any other product or service names, logos or slogans that may appear on DLIKE are trademarks of DLIKE and may not be copied, imitated or used, in whole or in part, without our prior written permission. You may not use any meta-tags or other "hidden text" utilizing "DLIKE" or any other name, trademark or product or service name of DLIKE without our prior written permission. </p>
		<p>In addition, the look and feel of DLIKE, including, without limitation, all page headers, custom graphics, button icons and scripts, constitute the service mark, trademark or trade dress of DLIKE and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and company names or logos mentioned or used on DLIKE are the property of their respective owners and may not be copied, imitated or used, in whole or in part, without the permission of the applicable trademark holder. Reference to any products, services, processes or other information by name, trademark, manufacturer and supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation by DLIKE.</p>
		<h2>5. No Liability For Third Party Services And Content</h2>
		<p>In using DLIKE Services, you may view content, advertisements, social "widgets" or utilize services provided by third parties, including links to web pages and services of such parties ("Third Party Content"). We do not control, endorse or adopt any Third-Party Content and will have no responsibility for Third Party Content including, without limitation, material that may be misleading, incomplete, erroneous, offensive, indecent or otherwise objectionable in your jurisdiction. In addition, your dealings or correspondence with such third parties are solely between you and the third parties. DLIKE is not responsible or liable for any loss or damage of any sort incurred as a result of any such dealings and you understand that your use of Third Party Content and your interactions with third parties is at your own risk.</p>
		<h2>6. Assumption of Risk, Limitations on Liability & Indemnity</h2>
		<p>6.1. You accept and acknowledge that there are risks associated with utilizing an Internet-based STEEM account service including, but not limited to, the risk of failure of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your Account, including, but not limited to your Private Key (as defined below under services). You accept and acknowledge that DLIKE will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Services, however caused.</p>
		<p>6.2. We will use reasonable endeavors to verify the accuracy of any information on the Service but we make no representation or warranty of any kind, express or implied, statutory or otherwise, regarding the contents of the Service, information and functions made accessible through the Service, any hyperlinks to third party websites, nor for any breach of security associated with the transmission of information through the Service or any website linked to by the Service.</p>
		<p>6.3. We will not be responsible or liable to you for any loss and take no responsibility for and will not be liable to you for any use of DLIKE Services, including but not limited to any losses, damages or claims arising from: (a) User error such as forgotten passwords, incorrectly constructed transactions, or mistyped STEEM addresses; (b) Server failure or data loss; (c) Corrupted Account files; (d) Unauthorized access to applications; (e) Any unauthorized third party activities, including without limitation the use of viruses, phishing, brute forcing or other means of attack against the Service or Services.</p>
		<p>6.4. We make no warranty that the Service or the server that makes it available, are free of viruses or errors, that its content is accurate, that it will be uninterrupted, or that defects will be corrected. We will not be responsible or liable to you for any loss of any kind, from action taken, or taken in reliance on material, or information, contained on the Service.</p>
		<p>6.5. Subject to 7.1 below, any and all indemnities, warranties, terms and conditions (whether express or implied) are hereby excluded to the fullest extent permitted under applicable law.</p>
		<p>6.6. We will not be liable, in contract, or tort (including, without limitation, negligence), other than where we have been fraudulent or made negligent misrepresentations.</p>
		<p>6.7. Nothing in these Terms excludes or limits liability for death or personal injury caused by negligence, fraudulent misrepresentation, or any other liability which may not otherwise be limited or excluded under applicable law.</p>
		<h2>7. Agreement to Hold DLIKE Harmless</h2>
		<p>7.1. You agree to hold harmless DLIKE (and each of our officers, directors, members, employees, moderators, agents and affiliates) from any claim, demand, action, damage, loss, cost or expense, including without limitation reasonable legal fees, arising out or relating to:</p>
		<li>7.1.1. Your use of, or conduct in connection with, our Services;</li>
		<li>7.1.2. Any feedback or submissions you provide (see 17 below);</li>----------------
		<li>7.1.3. Your violation of these Terms; or</li>
		<li>7.1.4. Violation of any rights of any other person or entity.</li>
		<p>7.2. If you are obligated to indemnify us, we will have the right, in our sole discretion, to control any action or proceeding (at our expense) and determine whether we wish to settle it.</p>
		<h2>8. Adult-Oriented Content</h2>
		<p>DLIKE is intended for a general audience and as a result, some DLIKE Content may discuss or depict adult-oriented topics. We realize that this content may not be appropriate or desirable for some of our readers depending on their current location, age, background or personal views. As a result, we mark this content as Not Safe For Work ("NSFW").</p>
		<p>Marking DLIKE Content as NSFW does not prevent you from being able to access this content but, instead, helps you make informed decisions about the type of content you view on DLIKE. You understand and agree that you access content marked as NSFW at your own risk.</p>
		<h2>9. Account Registration</h2>
		<p>9.1. DLIKE is built on STEEM blockchain so to use DLIKE, you need a STEEM account.  DLIKE provides account creation services to register new STEEM account. When you create an Account, you are strongly advised to take the following precautions, as failure to do so may result in loss of access to, and/or control over, your Wallet: (a) You must save your master password securely as in case of loss, DLIKE will not be able to recover it for you as we do not save any of your password or other steem related keys.(b) Once asked for identity verification make sure to provide correct phone number; (c) We save your phone number in hashed form(md5) to ensure uniqueness of accounts and avoid spammers to use same number again to register new accounts; (d) maintain the security of your Account by protecting your Account password and access to your computer and your Account as it involves your wallet.</p>
		<p>9.2. You hereby accept and acknowledge that you take responsibility for all activities that occur under your Account and accept all risks of any authorized or unauthorized access to your Account, to the maximum extent permitted by law. You also accept and acknowledge that you have no objection on saving phone numbers by DLIKE in hashed form as this data (phone number)  is not shared publically or with any other users.</p>


		<h2>11. Fees for Using DLIKE Services</h2>
		<p>DLIEK takes 10% beneficiary reward out of total post upvotes. Out of this 10%, 9% is goes to main @dlike account to cover cost and pay to sponsors who delegated Steem Power. 1% which is accumulated in @dlike.fund account is paid to charities.</p>
		<h2>12. No Right To Cancel And Or Reverse Steem Transactions</h2>
		<p>If you use a Service to which Steem, Steem Dollars or Steem Power is transacted, you will not be able to change your mind once you have confirmed that you wish to proceed with the Service or transaction.</p>
		<h2>13. Discontinuation of Services</h2>
		<p>We may, in our sole discretion and without cost to you, with or without prior notice and at any time, modify or discontinue, temporarily or permanently, any portion of DLIKE Services. You are solely responsible for storing, outside of the Services, a backup of any Account and Private Key pair that you maintain in your Wallet.</p>
		<p>If you do not maintain a backup of your Account data outside of the Services, you will not be able to access Steem, Steem Dollars and Steem Power associated with any Account Name maintained in your Account in the event that we discontinue or deprecate the Services.</p>
		<h2>14. Suspension or Termination of Service</h2>
		<p>DLIKE reserves the right, without notice and in our sole discretion, to terminate your license to access and use DLIKE and to block or prevent your future access to and use of DLIKE. In the event of termination, your access to funds will depend on your access to your backup of your Account data including your Account Name and Private Keys on steemit wallet.</p>
		<h2>15. Modifications to DLIKE</h2>
		<p>DLIKE reserves the right to modify or discontinue, temporarily or permanently, DLIKE, or any features or portions of DLIKE, without prior notice. You agree that DLIKE will not be liable for any modification, suspension or discontinuance of DLIKE, or any part of DLIKE.</p>
		<h2>16. Limitation of Liability</h2>
		<p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL DLIKE OR THE DLIKE PARTIES BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE) OR OTHERWISE, ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, THE USE OF, OR INABILITY TO USE, DLIKE OR THE DLIKE CONTENT. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE AGGREGATE LIABILITY OF DLIKE OR THE DLIKE PARTIES, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY, ARISING OUT OF OR RELATING TO: (A) THE USE OF OR INABILITY TO USE DLIKE OR THE DLIKE CONTENT; OR (B) THESE TERMS EXCEED ANY COMPENSATION YOU PAY, IF ANY, TO DLIKE FOR ACCESS TO OR USE OF DLIKE.</p>
		<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OR ALL OF THE EXCLUSIONS AND LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU.</p>
		<h2>17. Disclaimers</h2>
		<p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, DLIKE AND THE DLIKE CONTENT ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE. DLIKE DOES NOT REPRESENT OR WARRANT THAT DLIKE AND THE DLIKE CONTENT: (A) WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE OR THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; AND (C) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOUR USE OF DLIKE AND THE DLIKE CONTENT IS SOLELY AT YOUR OWN RISK. SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF IMPLIED TERMS IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE DISCLAIMERS IN THIS SECTION MAY NOT APPLY TO YOU.</p>
		<h2>18. Severability</h2>
		<p>If any term, clause or provision of these Terms is deemed to be unlawful, void or for any reason unenforceable, then that term, clause or provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.</p>
		<h2>19. Questions & Contact Information</h2>
		<p>Questions or comments about DLIKE services can be directed to admin&#64;dlik.io</p>
		<P>If you wish to report abuses or copyright infrigement, PLEASE EMAIL admin&#64;dlik.io</p>

	</div>	
</div>
<?php include('template/footer7.php'); ?> 